### ISSUE TITLE
Config Omaha server Admin panel to allow/ deny access from internet

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha-server#143]
Finally, I have setuped and config server to work with my client application. Btw, still one problem remain: After deploy server in new dev server has support VPN access, now admin panel page (http; {DOCKER_HOST}:9090/admin ) may be access from both local access (though VPN channel) and public internet. So I want to config to only access it from secure VPN chanel, to avoid some security problem.

I've try to modify some nginx setting file in server directory, but has no result.
Please help me solve this problem. Thanks alot.

**Comment by namtb49** [comment]
Please help me to solve this problem.
Because my update server has been plannned for store and manipulate and some sensitive data such as user infomation, so I planned to setup some secure access for my server in provision. I want to only user with VPN (with desired IP address) may be able to access server admin panel, and deny other in non-secure public internet.

**Comment by kyakovenko** [comment]
Hello namtb49,

Is this problem still actual or not?

**Comment by kyakovenko** [comment]
Hello namtb49,

You can use the OMAHA_SERVER_PRIVATE environment variable, it is intended to activate or deactivate private URLs. You can also set the IS_PRIVATE variable directly in a settings file in order to do the same.

So I can suggest the following solution for your case:

- you can install two Omaha servers for public and private purposes
- the two servers should use the same database but they should be accessible by different URLs
- you can split access to them using VPN, AWS Security Groups or using your own firewalls or network settings
    - Public server should be accessible for everyone
    - Private server should be accessible only from the allowed IPs

To my mind it'll allow you to increase a security level of your server.
