### ISSUE TITLE
Big installer upload

### ISSUE THREAD

**Issue by yukels** [Crystalnix/omaha-server#156]
I successfully deployed omaha-server on aws. Evening looks good. But when I tried to add a new version the web client crashed on upload our installer (~48 Mb). The problem can be solved if I firstly upload something small and only after that change the version definition to the real installer file.

One more thing. I have to change the value of healthcheck_url to "/admin/login/" in the settings.yml file because omaha-server returns 302 for "/admin/" value. And this confuses ElasticBeanstalk service. Is it ok?

**Comment by kyakovenko** [comment]
Hello yukels,

Thank you for contacting our us!

Could you send us a stacktrace of such crash that we'll be able to check it and help you with it?

About a health check url, we would prefer to choose a lightweight url which returns minimum amount of content because AWS sends GET requests to check availability of the server. It means than quicker your server responses than better.

If you have any other questions, please, let us know.

**Comment by yukels** [comment]
Hi Kirill

Unfortunately we disassembled our AWS environment and as result we can't reproduce the problem and provide the stacktrace. If you can't replace it on your environment, please close the issue.
Have a nice day!
