### ISSUE TITLE
Feedback API

### ISSUE THREAD

**Issue by xDrFred** [Crystalnix/omaha-server#193]
Hey guys

I'm trying to send an feedback to the service but I can't find a API Controller or Web Request Handler which collects feedbacks.

Did I just overlook it or is there no support for this?

**Comment by kyakovenko** [comment]
Hello xDrFred,

thank you for contacting us!

A module containing feedback declarations is in the [omaha_server/feedback](https://github.com/Crystalnix/omaha-server/tree/master/omaha_server/feedback) folder and the [FeedbackFormView](https://github.com/Crystalnix/omaha-server/blob/master/omaha_server/feedback/views.py#L43) controller handles new feedbacks. This handler isn't a part of our api because we use it in our specific software so it returns just an ID of a new entry in raw format.

I hope, it'll help you. Please, let us know if you have any questions.

**Comment by xDrFred** [comment]
Thanks for the answer.
When I send the request below I get an 500 HTTP result.

> DecodeError at /service/feedback/
> Unexpected end-group tag.
> /usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py in MergeFromString, line 1011

Do I use the controll in a wrong way?

POST /service/feedback/ HTTP/1.1
Host: devomaha
Cache-Control: no-cache
Postman-Token: ed5f76bd-f09d-a495-0ddd-2fabe600ee14
Content-Type: application/x-www-form-urlencoded

description=My+test+description&email=email%40provider.com&page_url=asdasd&feedback_data=asdasdasdasdasdasd&id=192.168.1.162

**Comment by anmekin** [comment]
Hello xDrFred,

You should send request in the [protobuf](https://developers.google.com/protocol-buffers/) format. Please, pay additional attention that you should send a protobuf file as a binary file and set content_type='application/x-protobuf'. 

You can find more details in [our unit test](https://github.com/Crystalnix/omaha-server/blob/master/omaha_server/feedback/tests/test_views.py). You can also test this function using our [test protobuf file](https://github.com/Crystalnix/omaha-server/blob/master/omaha_server/feedback/tests/testdata/request.pb).

**Comment by xDrFred** [comment]
I got the request working with the test data but strugle to write an Interface in c# for the Feedback data.
This is most likely because I'm new to protocol buffers and can find the type definition.
Can somebody show me the right path?

```
using ProtoBuf;

[ProtoContract]
public class Feedback
{
    //which members and with which tag index?
}
```

**Comment by xDrFred** [comment]
Hey Together

When I'm using "ExtensionSubmit" or "SuggestQuery" messages everything works fine.. It just took me a while to understand which message has to be submitted.
