### ISSUE TITLE
Feature request: version and crash management scheme

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#95]
Need a way to limit the storage size for versions and crashes.

**Comment by kyakovenko** [comment]
Hello Chad,

Could you give us some more explanations?
Particularly, I would like to know what is a goal which you want to reach by using such limit for the storage size. The point is that if you want just control a size of all files stored in S3, it possibly could be valuable to use a monitoring system. As I know, AWS has utilities helping to manage budgets and limits. On the other hand, if you want to restrict the number of entries in a database or a storage size in order to automate this process and get rid of manual management, it will better to implement this feature on the server side. In any case, we need to get answers to the following questions:

1. Would you like to change a limit through admin dashboard or it would be enough if we put this to settings file?
2. How should we delete these files, we should delete files until there is sufficient space to store new one or we should just delete the oldest by criteria?

Best regards,
Kirill Yakovenko

**Comment by anmekin** [comment]
#116
